<a href="https://colab.research.google.com/github/sharvani1357/mental_health_final_rnn/blob/main/AI_Based_Mental_Health_Sentiment_Monitoring_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub
import os
import pandas as pd
# DOWNLOAD DATASET
path = kagglehub.dataset_download("suchintikasarkar/sentiment-analysis-for-mental-health")
print("Dataset Path:\n")
print(path)
# SHOW FILES INSIDE DATASET
print("\nFiles Inside Dataset:\n")
print(os.listdir(path))

# FIND CSV FILE
csv_file = None
for file in os.listdir(path):
    if file.endswith(".csv"):
        csv_file = file

# LOAD DATASET
dataset_path = os.path.join(path,csv_file)
df = pd.read_csv(dataset_path)

# DISPLAY FIRST 5 ROWS
print("\nFirst 5 Rows:\n")
print(df.head())

# DATASET SHAPE
print("\nDataset Shape:\n")
print(df.shape)

# COLUMN NAMES
print("\nColumn Names:\n")
print(df.columns)

# CHECK MISSING VALUES
print("\nMissing Values:\n")
print(df.isnull().sum())


# NUMBER OF SENTIMENT CLASSES
print("\nSentiment Classes:\n")
print(df['status'].unique())
print("\nNumber of Classes:\n")
print(df['status'].nunique())


# CLASS DISTRIBUTION
print("\nClass Distribution:\n")
print(df['status'].value_counts())


# AVERAGE SENTENCE LENGTH
df['sentence_length'] = df['statement'].apply(lambda x: len(str(x).split()))
print("\nAverage Sentence Length:\n")
print(df['sentence_length'].mean())


# MAXIMUM SENTENCE LENGTH
print("\nMaximum Sentence Length:\n")
print(df['sentence_length'].max())


# MINIMUM SENTENCE LENGTH
print("\nMinimum Sentence Length:\n")
print(df['sentence_length'].min())

Using Colab cache for faster access to the 'sentiment-analysis-for-mental-health' dataset.
Dataset Path:

/kaggle/input/sentiment-analysis-for-mental-health

Files Inside Dataset:

['Combined Data.csv']

First 5 Rows:

   Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3           3  I've shifted my focus to something else but I'...  Anxiety
4           4  I'm restless and restless, it's been a month n...  Anxiety

Dataset Shape:

(53043, 3)

Column Names:

Index(['Unnamed: 0', 'statement', 'status'], dtype='object')

Missing Values:

Unnamed: 0      0
statement     362
status          0
dtype: int64

Sentiment Classes:

['Anxiety' 'Normal' 'Depression' 'Suicidal' 'Stress' 'Bipolar'
 'Personality disorder']

Number of Classes:

7

Class Distribu

In [3]:
import nltk
import re
import string

from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Download stopwords dataset
nltk.download('stopwords')

# Get text column from dataset
text_data = df['statement'].astype(str)

# Load stopwords
stop_words = set(stopwords.words('english'))

# Store cleaned sentences
cleaned_sentences = []

# Loop through every sentence
for sentence in text_data:

    # Convert text to lowercase
    sentence = sentence.lower()

    # Remove punctuation symbols
    sentence = re.sub(
        f"[{string.punctuation}]","",sentence)

    # Split sentence into words
    words = sentence.split()

    # Store filtered words
    filtered_words = []

    # Remove stopwords
    for word in words:
          if word not in stop_words:
            filtered_words.append(word)

    # Join words back into sentence
    cleaned_sentence = " ".join(filtered_words)

    # Add cleaned sentence to list
    cleaned_sentences.append(cleaned_sentence)

# Display sample cleaned text
print("\nCleaned Text Samples:\n")

for i in range(5):
  print(cleaned_sentences[i])

# Create tokenizer object
tokenizer = Tokenizer()

# Build vocabulary from text
tokenizer.fit_on_texts(cleaned_sentences)

# Convert text into numerical sequences
sequences = tokenizer.texts_to_sequences(cleaned_sentences)

# Display sample sequences
print("\nSample Sequences:\n")

print(sequences[:5])

# Store vocabulary dictionary
word_index = tokenizer.word_index

# Display vocabulary size
print("\nVocabulary Size:\n")

print(len(word_index))

# Set fixed sequence length
max_length = 50

# Apply padding to make all sequences same length
padded_sequences = pad_sequences(sequences,maxlen=max_length,padding='post')

# Display padded sequence shape
print("\nPadded Sequence Shape:\n")

print(padded_sequences.shape)

# Display sample padded sequence
print("\nSample Padded Sequence:\n")
print(padded_sequences[0])



[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.



Cleaned Text Samples:

oh gosh
trouble sleeping confused mind restless heart tune
wrong back dear forward doubt stay restless restless place
ive shifted focus something else im still worried
im restless restless month boy mean

Sample Sequences:

[[494, 4667], [808, 519, 834, 157, 1108, 193, 8564], [169, 26, 2114, 471, 1007, 236, 1108, 1108, 182], [92, 7142, 569, 32, 83, 15, 30, 306], [15, 1108, 1108, 183, 1231, 272]]

Vocabulary Size:

81079

Padded Sequence Shape:

(53043, 50)

Sample Padded Sequence:

[ 494 4667    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0]


In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(cleaned_sentences)
print("Vocabulary:\n")
print(tokenizer.word_index)
print("\nVocabulary Size:\n")
print(len(tokenizer.word_index))

Vocabulary:

{'like': 1, 'feel': 2, 'want': 3, 'know': 4, 'life': 5, 'get': 6, 'even': 7, 'time': 8, 'would': 9, 'people': 10, 'really': 11, 'cannot': 12, 'one': 13, 'going': 14, 'im': 15, 'think': 16, 'go': 17, 'much': 18, 'never': 19, 'day': 20, 'help': 21, 'things': 22, 'could': 23, 'years': 24, 'anymore': 25, 'back': 26, 'anxiety': 27, 'work': 28, 'anything': 29, 'still': 30, 'make': 31, 'something': 32, 'depression': 33, 'friends': 34, 'got': 35, 'always': 36, 'good': 37, 'take': 38, 'anyone': 39, 'feeling': 40, 'way': 41, 'everything': 42, 'better': 43, 'i’m': 44, 'every': 45, 'need': 46, 'see': 47, 'nothing': 48, 'someone': 49, 'also': 50, 'bad': 51, 'year': 52, 'since': 53, 'family': 54, 'right': 55, 'dont': 56, 'last': 57, 'hate': 58, 'thing': 59, 'live': 60, 'job': 61, 'fucking': 62, 'getting': 63, 'love': 64, 'end': 65, 'die': 66, 'ever': 67, 'talk': 68, 'everyone': 69, 'thought': 70, 'lot': 71, 'long': 72, 'say': 73, 'trying': 74, 'tired': 75, 'person': 76, 'started': 77, '

In [5]:
word_index = tokenizer.word_index
print("Word Index:\n")
for word, index in list(word_index.items())[:20]:
    print(word, ":", index)

Word Index:

like : 1
feel : 2
want : 3
know : 4
life : 5
get : 6
even : 7
time : 8
would : 9
people : 10
really : 11
cannot : 12
one : 13
going : 14
im : 15
think : 16
go : 17
much : 18
never : 19
day : 20


In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length = 50
padded_sequences = pad_sequences(sequences,maxlen=max_length,padding='post')
print("Padded Sequence Shape:\n")
print(padded_sequences.shape)
print("\nSample Padded Sequence:\n")
print(padded_sequences[0])

Padded Sequence Shape:

(53043, 50)

Sample Padded Sequence:

[ 494 4667    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0]


In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense
vocab_size = len(word_index) + 1
model = Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=128,input_length=50))
model.add(SimpleRNN(64))
model.add(Dense(32,activation='relu'))
model.add(Dense(df['status'].nunique(),activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df['status'])
X = padded_sequences
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
optimizer = Adam(learning_rate=0.001)
model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer,metrics=['accuracy'])
history = model.fit(X_train,y_train,validation_split=0.2,epochs=5,batch_size=32)

Epoch 1/5
1061/1061 ━━━━━━━━━━━━━━━━━━━━ 15s 10ms/step - accuracy: 0.4396 - loss: 1.5032 - val_accuracy: 0.4493 - val_loss: 1.4844
Epoch 2/5
1061/1061 ━━━━━━━━━━━━━━━━━━━━ 16s 8ms/step - accuracy: 0.4679 - loss: 1.4178 - val_accuracy: 0.4528 - val_loss: 1.4216
Epoch 3/5
1061/1061 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.5124 - loss: 1.3028 - val_accuracy: 0.4639 - val_loss: 1.4226
Epoch 4/5
1061/1061 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.5628 - loss: 1.1893 - val_accuracy: 0.4728 - val_loss: 1.4461
Epoch 5/5
1061/1061 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6109 - loss: 1.0771 - val_accuracy: 0.4695 - val_loss: 1.5313


In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
prediction = model.predict(X_test)
y_pred = np.argmax(prediction,axis=1)
accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred,average='weighted')
recall = recall_score(y_test,y_pred,average='weighted')
f1 = f1_score(y_test,y_pred,average='weighted')
cm = confusion_matrix(y_test,y_pred)
print("Accuracy:\n")
print(accuracy)
print("\nPrecision:\n")
print(precision)
print("\nRecall:\n")
print(recall)
print("\nF1 Score:\n")
print(f1)
print("\nConfusion Matrix:\n")
print(cm)
print("\nClassification Report:\n")
print(classification_report(y_test,y_pred))

332/332 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step
Accuracy:

0.4765764916580262

Precision:

0.48191524466171604

Recall:

0.4765764916580262

F1 Score:

0.42297713643306334

Confusion Matrix:

[[ 208   91   70  360   15   29    6]
 [ 113  133   75  220   17   11   11]
 [  71   70  910 1448   21   12  568]
 [  13   14   24 3259    2    5   10]
 [  30   23   31  115   30    6   13]
 [  63   39   43  325   12   60   15]
 [   4    3  405 1145    3    2  456]]

Classification Report:

              precision    recall  f1-score   support

           0       0.41      0.27      0.32       779
           1       0.36      0.23      0.28       580
           2       0.58      0.29      0.39      3100
           3       0.47      0.98      0.64      3327
           4       0.30      0.12      0.17       248
           5       0.48      0.11      0.18       557
           6       0.42      0.23      0.29      2018

    accuracy                           0.48     10609
   macro avg       0.43      0.32 

In [14]:
user_sentence = input("Enter a sentence:\n")
words = user_sentence.split()
print("\nInput Sentence:\n")
print(user_sentence)
print("\nSequential Learning Process:\n")
hidden_state = ""
for word in words:
    hidden_state = hidden_state + " " + word
    print("Current Word:\n")
    print(word)
    print("\nHidden State Memory:\n")
    print(hidden_state)
    print("\n-------------------")
print("\nRNN remembers previous words using hidden state.")


Enter a sentence:
i am sad

Input Sentence:

i am sad

Sequential Learning Process:

Current Word:

i

Hidden State Memory:

 i

-------------------
Current Word:

am

Hidden State Memory:

 i am

-------------------
Current Word:

sad

Hidden State Memory:

 i am sad

-------------------

RNN remembers previous words using hidden state.


In [15]:
import numpy as np
user_sentence = input("Enter your sentence:\n")
processed_text = user_sentence.lower()
sequence = tokenizer.texts_to_sequences([processed_text])
padded_sequence = pad_sequences(sequence,maxlen=50,padding='post')
prediction = model.predict(padded_sequence)
predicted_class = np.argmax(prediction,axis=1)
predicted_label = label_encoder.inverse_transform(predicted_class)
confidence_score = np.max(prediction) * 100
print("\nUser Sentence:\n")
print(user_sentence)
print("\nPredicted Emotion:\n")
print(predicted_label[0])
print("\nConfidence Score:\n")
print(confidence_score)


Enter your sentence:
i am not good
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

User Sentence:

i am not good

Predicted Emotion:

Normal

Confidence Score:

51.071793


In [16]:
import pickle

model.save(
    "mental_health_rnn_model.h5"
)

with open(
    "tokenizer.pkl",
    "wb"
) as file:

    pickle.dump(
        tokenizer,
        file
    )

with open(
    "label_encoder.pkl",
    "wb"
) as file:

    pickle.dump(
        label_encoder,
        file
    )

print("Model Saved Successfully")

print("Tokenizer Saved Successfully")

print("Label Encoder Saved Successfully")

print("\nTASK 9 COMPLETED SUCCESSFULLY")

Model Saved Successfully
Tokenizer Saved Successfully
Label Encoder Saved Successfully

TASK 9 COMPLETED SUCCESSFULLY
